name: Silhouettes
author: K1r1too
flag: IEEE{Tr4c1ng_s1lhOu3ttEs_Of_y0oOuUuUu}
description: |
  But my anxieties have promised me the worst is to come.

  Note:the flag is the correct input wrapped with the flag format IEEE{<phrase>}